#!/usr/bin/env python3
"""Validate that a document generated by the athena skill has the sections it must.

Standard library only. No third-party packages, no network access.

Usage:
    python3 validate_doc.py FILE --type {readme,deploy-guide,kba}
    python3 validate_doc.py FILE --type kba --strict
    python3 validate_doc.py FILE --type readme --json

Exit codes:
    0  document has every required section, in the required order
    1  document is missing sections, has them out of order, or (with --strict)
       still contains unresolved placeholders or TODO markers
    2  usage error -- file unreadable, unknown type, bad arguments
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# --- Section contracts -------------------------------------------------------
# Keep these in lockstep with references/<type>-spec.md. Adding a doc type means
# adding one entry here, one reference spec, and one template. See CONTRIBUTING.md.

SPEC = {
    "readme": {
        "required": [
            "Overview",
            "Requirements",
            "Installation",
            "Usage",
            "License",
        ],
        "optional": ["Configuration", "Troubleshooting", "Contributing"],
        "order": [
            "Overview",
            "Requirements",
            "Installation",
            "Usage",
            "Configuration",
            "Troubleshooting",
            "Contributing",
            "License",
        ],
    },
    "deploy-guide": {
        "required": [
            "Overview",
            "Prerequisites",
            "Installation",
            "Verification",
            "Rollback",
        ],
        "optional": ["Ports and Firewall", "Configuration", "Troubleshooting"],
        "order": [
            "Overview",
            "Prerequisites",
            "Ports and Firewall",
            "Installation",
            "Configuration",
            "Verification",
            "Rollback",
            "Troubleshooting",
        ],
    },
    "kba": {
        "required": [
            "Summary",
            "Environment",
            "Symptom",
            "Root Cause",
            "Resolution",
            "Verification",
        ],
        "optional": ["Diagnostic Steps", "Workaround", "Related Articles"],
        "order": [
            "Summary",
            "Environment",
            "Symptom",
            "Diagnostic Steps",
            "Root Cause",
            "Workaround",
            "Resolution",
            "Verification",
            "Related Articles",
        ],
    },
}

PLACEHOLDER_RE = re.compile(r"<[A-Z][A-Z0-9_]{2,}>")
TODO_RE = re.compile(r"\bTODO\b")
VERIFY_RE = re.compile(r"<!--\s*verify")
FENCE_RE = re.compile(r"^\s*(?P<marker>`{3,}|~{3,})\s*(?P<info>.*?)\s*$")
H1_RE = re.compile(r"^#\s+(?P<title>.+?)\s*$")
H2_RE = re.compile(r"^##\s+(?P<title>.+?)\s*$")
INLINE_COMMENT_RE = re.compile(r"<!--.*?-->")
HTML_COMMENT_OPEN_RE = re.compile(r"<!--")
HTML_COMMENT_CLOSE_RE = re.compile(r"-->")


def _clean_heading(title: str) -> str:
    """Strip inline HTML comments from a heading so a `<!-- verify -->` marker
    on the heading line does not change the section name."""
    return INLINE_COMMENT_RE.sub("", title).strip()


def parse_document(text: str) -> dict:
    """Return H1 title, ordered H2 section names, and marker line numbers.

    Headings inside fenced code blocks are ignored, so a spec's worked example
    does not register as a real section.
    """
    h1 = None
    sections: list[str] = []
    placeholders: list[tuple[int, str]] = []
    todos: list[int] = []
    verifies: list[int] = []

    in_fence = False
    fence_char = ""
    fence_len = 0
    in_comment = False

    for lineno, raw in enumerate(text.splitlines(), start=1):
        fence = FENCE_RE.match(raw)
        if fence:
            marker = fence.group("marker")
            info = fence.group("info")
            if not in_fence:
                in_fence, fence_char, fence_len = True, marker[0], len(marker)
                continue
            if marker[0] == fence_char and len(marker) >= fence_len and not info:
                in_fence, fence_char, fence_len = False, "", 0
                continue

        if not in_fence:
            if in_comment:
                if HTML_COMMENT_CLOSE_RE.search(raw):
                    in_comment = False
                continue
            if HTML_COMMENT_OPEN_RE.search(raw) and not HTML_COMMENT_CLOSE_RE.search(raw):
                if VERIFY_RE.search(raw):
                    verifies.append(lineno)
                in_comment = True
                continue

            if h1 is None:
                m = H1_RE.match(raw)
                if m:
                    h1 = _clean_heading(m.group("title"))
                    if VERIFY_RE.search(raw):
                        verifies.append(lineno)
                    continue
            m = H2_RE.match(raw)
            if m:
                sections.append(_clean_heading(m.group("title")))
                if VERIFY_RE.search(raw):
                    verifies.append(lineno)
                continue

        for hit in PLACEHOLDER_RE.findall(raw):
            placeholders.append((lineno, hit))
        if TODO_RE.search(raw):
            todos.append(lineno)
        if VERIFY_RE.search(raw):
            verifies.append(lineno)

    return {
        "h1": h1,
        "sections": sections,
        "placeholders": placeholders,
        "todos": todos,
        "verifies": verifies,
    }


def validate(parsed: dict, doc_type: str, strict: bool) -> tuple[list[str], list[str]]:
    """Return (errors, warnings)."""
    spec = SPEC[doc_type]
    errors: list[str] = []
    warnings: list[str] = []

    if not parsed["h1"]:
        errors.append("missing H1 title (a line starting with '# ')")

    found = parsed["sections"]
    found_set = set(found)

    missing = [s for s in spec["required"] if s not in found_set]
    for section in missing:
        errors.append(f"missing required section: ## {section}")

    known = set(spec["required"]) | set(spec["optional"])
    seen_unknown: set[str] = set()
    for section in found:
        if section not in known and section not in seen_unknown:
            seen_unknown.add(section)
            warnings.append(
                f"unrecognised section: ## {section} "
                f"(not in the {doc_type} spec; check the heading text)"
            )

    dupes = sorted({s for s in found if found.count(s) > 1})
    for section in dupes:
        errors.append(f"duplicate section: ## {section}")

    canonical = [s for s in spec["order"] if s in found_set]
    present: list[str] = []
    for section in found:
        if section in known and section not in present:
            present.append(section)
    if present != canonical:
        errors.append(
            "sections are out of order\n"
            f"    found:    {' -> '.join(present)}\n"
            f"    expected: {' -> '.join(canonical)}"
        )

    if parsed["placeholders"]:
        detail = ", ".join(f"{name} (line {ln})" for ln, name in parsed["placeholders"][:10])
        more = "" if len(parsed["placeholders"]) <= 10 else f" +{len(parsed['placeholders']) - 10} more"
        msg = f"unresolved placeholders: {detail}{more}"
        (errors if strict else warnings).append(msg)

    if parsed["todos"]:
        lines = ", ".join(str(ln) for ln in parsed["todos"][:10])
        msg = f"TODO markers on line(s): {lines}"
        (errors if strict else warnings).append(msg)

    if parsed["verifies"]:
        lines = ", ".join(str(ln) for ln in parsed["verifies"][:10])
        warnings.append(f"{len(parsed['verifies'])} inferred value(s) need human review, line(s): {lines}")

    return errors, warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="validate_doc.py",
        description="Check that an athena-generated document has its required sections.",
    )
    parser.add_argument("file", help="path to the Markdown document to validate")
    parser.add_argument(
        "--type",
        required=True,
        choices=sorted(SPEC),
        dest="doc_type",
        help="document type to validate against",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="treat unresolved placeholders and TODO markers as errors",
    )
    parser.add_argument("--json", action="store_true", help="emit a JSON report instead of text")
    args = parser.parse_args(argv)

    path = Path(args.file)
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"error: cannot read {path}: {exc}", file=sys.stderr)
        return 2

    parsed = parse_document(text)
    errors, warnings = validate(parsed, args.doc_type, args.strict)
    ok = not errors

    if args.json:
        print(
            json.dumps(
                {
                    "file": str(path),
                    "type": args.doc_type,
                    "ok": ok,
                    "title": parsed["h1"],
                    "sections": parsed["sections"],
                    "errors": errors,
                    "warnings": warnings,
                },
                indent=2,
            )
        )
        return 0 if ok else 1

    label = "PASS" if ok else "FAIL"
    print(f"{label}  {path}  (type: {args.doc_type})")
    if parsed["h1"]:
        print(f"  title: {parsed['h1']}")
    print(f"  sections: {', '.join(parsed['sections']) or '(none)'}")
    for err in errors:
        print(f"  ERROR   {err}")
    for warn in warnings:
        print(f"  WARN    {warn}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
